openapi: 3.0.3
info:
  title: Pricing API
  version: 1.0.0

paths:
  /prices:
    get:
      tags:
        - PricesSpec
      operationId: getPrices
      summary: Consulta precio por fecha, producto y marca
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
        - in: query
          name: brandId
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: productId
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description: Precio encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '204':
          description: No se encontr칩 tarifa aplicable
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  responses:
    BadRequest:
      description: Par치metros inv치lidos
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
    NotFound:
      description: No se encontr칩 el recurso solicitado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
    InternalError:
      description: Error interno del servidor
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'

  schemas:
    PriceResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceList:
          type: integer
        startDate:
          type: string
        endDate:
          type: string
        price:
          type: number
          format: double

    ApiErrorResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        timestamp:
          type: string
          format: date-time
