CREATE TABLE PRICES (
    BRAND_ID     INT NOT NULL,
    START_DATE   TIMESTAMP NOT NULL,
    END_DATE     TIMESTAMP NOT NULL,
    PRICE_LIST   INT NOT NULL,
    PRODUCT_ID   INT NOT NULL,
    PRIORITY     INT NOT NULL,
    PRICE        DECIMAL(10, 2) NOT NULL,
    CURRENCY     VARCHAR(3) NOT NULL,

    PRIMARY KEY (BRAND_ID, PRODUCT_ID, START_DATE, PRICE_LIST)
);
CREATE TABLE BRAND (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

ALTER TABLE PRICES
ADD CONSTRAINT FK_PRICES_BRAND
FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID);

CREATE INDEX idx_price_lookup ON prices (product_id, brand_id, start_date, end_date, priority);
